// import "oaidl.idl";
// import "ocidl.idl";

cpp_quote("//-------------------------------------------------------")
cpp_quote("//-------------------------------------------------------")
cpp_quote("//-------------------------------------------------------")
cpp_quote("// (c) 2004, 2006 by DBJSolutions Ltd.")
cpp_quote("// (c) 2020, 2022 by DBJSystems   Ltd.")
cpp_quote("//-------------------------------------------------------")
cpp_quote("//-------------------------------------------------------")
cpp_quote("//-------------------------------------------------------")

[
  uuid(ED07766C-88E5-3B40-A349-B2F1027AD633),
  version(5.0),
  helpstring("DBJ's Integration Interfaces, (c) by DBJSolutions Ltd., DBJSystems Ltd."),
]
library dbjinterpoint
{
    importlib("stdole2.tlb");

    interface IPoint;

    [
      object,
      uuid(D1A56BFD-C8D5-47CE-B077-0352B1223BF1),
	  helpstring("Integration Point interface")
    ]
    interface IPoint : IDispatch {
        [id(1),
			  helpstring("method call")
		]
        long call(
        [in] BSTR request_for_external_system, 
        [out] BSTR* response_from_external_system
		) ;
    };
};
